import type { DrawingElement, EditorProject, PlaceNode, RegionShape } from "../../model/project-model";
import { pointInRegion, regionGeoJson, shapePolygons } from "../../geometry/region-constraints";
import { sampleBezier } from "../../geometry/bezier-geometry";
import { relativePlaceMatrix, transformDrawingGeometry, transformRegion } from "../../geometry/affine-transform";
import { distance, polylineDistance } from "./geometry";
import { storyAccessDecision } from "./access";
import GeometryFactory from "jsts/org/locationtech/jts/geom/GeometryFactory.js";
import GeoJSONReader from "jsts/org/locationtech/jts/io/GeoJSONReader.js";
import GeoJSONWriter from "jsts/org/locationtech/jts/io/GeoJSONWriter.js";
import BufferOp from "jsts/org/locationtech/jts/operation/buffer/BufferOp.js";
import SnapIfNeededOverlayOp from "jsts/org/locationtech/jts/operation/overlay/snap/SnapIfNeededOverlayOp.js";
import { regionShapesFromGeoJson } from "../../geometry/region-constraints";
import type { StoryRouteAlternative, StoryRouteOptions, StoryRouteRequest } from "./types";
import { routeWidth } from "./width";
import { outdoorVisibilityPath } from "./outdoor-visibility";
import { outdoorElementSemantics, routeElementRibbonWidth, routeElementWidthCap } from "./outdoor-element-semantics";

export { isWaterTerrainElement } from "./outdoor-element-semantics";

type Point = { x: number; y: number };
type Obstacle = { id: string; shape: RegionShape; water?: boolean };
type Road = { element: DrawingElement; path: Point[] };
const factory = new GeometryFactory(); const reader = new GeoJSONReader(factory); const writer = new GeoJSONWriter();
type SpatialGeometry = ReturnType<GeoJSONReader["read"]>;
type Bounds = { minX: number; minY: number; maxX: number; maxY: number };
type PreparedRegion = { shape: RegionShape; geometry: SpatialGeometry; bounds: Bounds; pointMembership: WeakMap<Point, boolean> };
type PreparedObstacle = Obstacle & { geometry: SpatialGeometry; bounds: Bounds };
function transformedPath(project: EditorProject, ownerId: string, element: DrawingElement) { const source = project.places.some(({ id }) => id === element.belongsToId) ? element.belongsToId : ownerId; const geometry = transformDrawingGeometry(relativePlaceMatrix(project, ownerId, source), element.geometry); return geometry.kind === "path" ? geometry.points : geometry.kind === "bezier" ? sampleBezier(geometry.nodes, false) : []; }
function ribbonShape(path: Point[], width: number): RegionShape | undefined { if (path.length < 2) return undefined; const geometry = reader.read({ type: "LineString", coordinates: path.map(({ x, y }) => [x, y]) }); const buffered = BufferOp.bufferOp(geometry, Math.max(.01, width / 2), 8); return regionShapesFromGeoJson(writer.write(buffered) as Parameters<typeof regionShapesFromGeoJson>[0])[0]; }
function shapeBounds(shape: RegionShape): Bounds { const points = shapePolygons(shape).flatMap(({ outer }) => outer); return points.reduce((result, point) => ({ minX: Math.min(result.minX, point.x), minY: Math.min(result.minY, point.y), maxX: Math.max(result.maxX, point.x), maxY: Math.max(result.maxY, point.y) }), { minX: Infinity, minY: Infinity, maxX: -Infinity, maxY: -Infinity }); }
function expandedBounds(bounds: Bounds, amount: number): Bounds { return { minX: bounds.minX - amount, minY: bounds.minY - amount, maxX: bounds.maxX + amount, maxY: bounds.maxY + amount }; }
function overlaps(first: Bounds, second: Bounds) { return first.minX <= second.maxX + 1e-9 && first.maxX + 1e-9 >= second.minX && first.minY <= second.maxY + 1e-9 && first.maxY + 1e-9 >= second.minY; }
function segmentBounds(a: Point, b: Point, clearance: number): Bounds { return expandedBounds({ minX: Math.min(a.x, b.x), minY: Math.min(a.y, b.y), maxX: Math.max(a.x, b.x), maxY: Math.max(a.y, b.y) }, clearance); }
function preparedRegion(shape: RegionShape): PreparedRegion { return { shape, geometry: reader.read(regionGeoJson(shape)), bounds: shapeBounds(shape), pointMembership: new WeakMap() }; }
function pointInside(point: Point, region: PreparedRegion) {
  const cached = region.pointMembership.get(point);
  if (cached !== undefined) return cached;
  // Keep pointInRegion's edge-length-dependent boundary tolerance for every shape.
  const inside = pointInRegion(point, region.shape);
  region.pointMembership.set(point, inside);
  return inside;
}
function bounds(owner: PlaceNode, request: StoryRouteRequest, obstacles: Obstacle[]) { const points = [request.from.point, request.to.point, ...obstacles.flatMap(({ shape }) => shapePolygons(shape).flatMap(({ outer }) => outer))]; const margin = 20 + routeWidth(request) * 2; const xs = points.map(({ x }) => x); const ys = points.map(({ y }) => y); return owner.boundary ?? { kind: "rectangle" as const, x: Math.min(...xs) - margin, y: Math.min(...ys) - margin, width: Math.max(1, Math.max(...xs) - Math.min(...xs) + margin * 2), height: Math.max(1, Math.max(...ys) - Math.min(...ys) + margin * 2) }; }
function line(a: Point, b: Point) { return reader.read({ type: "LineString", coordinates: [[a.x, a.y], [b.x, b.y]] }); }
function intersects(segment: SpatialGeometry, probe: SpatialGeometry, shape: SpatialGeometry) { const crossed = SnapIfNeededOverlayOp.intersection(probe, shape) as unknown as { getArea(): number; isEmpty(): boolean }; const hit = crossed.getArea() > 1e-7 || (probe as unknown as { getArea(): number }).getArea() === 0 && !(SnapIfNeededOverlayOp.intersection(segment, shape) as unknown as { isEmpty(): boolean }).isEmpty(); return { hit, crossed }; }
function covered(crossedWater: { getArea(): number; isEmpty(): boolean }, bridge: SpatialGeometry) { if (crossedWater.isEmpty()) return true; return (SnapIfNeededOverlayOp.intersection(crossedWater, bridge) as unknown as { getArea(): number }).getArea() + Math.max(1e-7, crossedWater.getArea() * 1e-5) >= crossedWater.getArea(); }
function inside(segment: SpatialGeometry, probe: SpatialGeometry, boundary: SpatialGeometry, clearance: number) { const length = (segment as unknown as { getLength(): number }).getLength(); const clipped = SnapIfNeededOverlayOp.intersection(boundary, segment) as unknown as { getLength(): number; isEmpty(): boolean }; if (clipped.isEmpty() || clipped.getLength() + 1e-7 < length) return false; if (!clearance) return true; const area = (probe as unknown as { getArea(): number }).getArea(); return (SnapIfNeededOverlayOp.intersection(boundary, probe) as unknown as { getArea(): number }).getArea() + Math.max(1e-7, area * 1e-5) >= area; }
function openSegment(a: Point, b: Point, boundary: PreparedRegion, obstacles: PreparedObstacle[], bridges: PreparedRegion[], clearance: number) { if (!pointInside(a, boundary) || !pointInside(b, boundary)) return false; const probeBounds = segmentBounds(a, b, clearance); const relevant = obstacles.filter((obstacle) => overlaps(probeBounds, obstacle.bounds)); const rectangularBoundary = boundary.shape.kind === "rectangle" && probeBounds.minX >= boundary.shape.x - 1e-9 && probeBounds.maxX <= boundary.shape.x + boundary.shape.width + 1e-9 && probeBounds.minY >= boundary.shape.y - 1e-9 && probeBounds.maxY <= boundary.shape.y + boundary.shape.height + 1e-9; if (rectangularBoundary && !relevant.length) return true; const segment = line(a, b); const probe = clearance ? BufferOp.bufferOp(segment, clearance, 8) : segment; if (!rectangularBoundary && !inside(segment, probe, boundary.geometry, clearance)) return false; return !relevant.some((obstacle) => { const crossing = intersects(segment, probe, obstacle.geometry); if (!crossing.hit) return false; return !(obstacle.water && bridges.some((bridge) => overlaps(probeBounds, bridge.bounds) && covered(crossing.crossed, bridge.geometry))); }); }
function candidatePoints(boundary: RegionShape, obstacles: Obstacle[], bridges: RegionShape[], roads: Road[], margin: number) { const points = shapePolygons(boundary).flatMap(({ outer }) => outer); for (const shape of [...obstacles.map(({ shape }) => shape), ...bridges]) for (const ring of shapePolygons(shape).map(({ outer }) => outer)) { const centre = ring.reduce((sum, p) => ({ x: sum.x + p.x, y: sum.y + p.y }), { x: 0, y: 0 }); for (const p of ring) { const length = Math.hypot(p.x - centre.x, p.y - centre.y) || 1; points.push({ x: p.x + (p.x - centre.x) / length * margin, y: p.y + (p.y - centre.y) / length * margin }, { x: p.x + margin, y: p.y }, { x: p.x - margin, y: p.y }, { x: p.x, y: p.y + margin }, { x: p.x, y: p.y - margin }); } } for (const road of roads) points.push(...road.path); return points.filter((point) => pointInRegion(point, boundary)); }
function visibility(boundary: PreparedRegion, obstacles: PreparedObstacle[], bridges: PreparedRegion[], from: Point, to: Point, candidates: Point[], clearance: number) {
  return outdoorVisibilityPath(from, to, candidates, (a, b) => openSegment(a, b, boundary, obstacles, bridges, clearance));
}
function accessAllowed(project: EditorProject, owner: PlaceNode, request: StoryRouteRequest, options: StoryRouteOptions) { const custom = options.access?.({ kind: "place", id: owner.id, scopeId: owner.id, access: owner.access, locked: false }, { actorId: request.actorId, scenarioId: request.scenarioId, stepId: request.stepId }); if (custom !== undefined) return custom === true || typeof custom !== "boolean" && custom.allowed; const result = storyAccessDecision(project, { kind: "place", id: owner.id, scopeId: owner.id }, { actorId: request.actorId, scenarioId: request.scenarioId, stepId: request.stepId }); return result === true || typeof result !== "boolean" && result.allowed; }
function nearestOnPath(point: Point, path: Point[]) { let best = { point: path[0]!, index: 0, distance: Infinity }; for (let index = 0; index + 1 < path.length; index += 1) { const a = path[index]!; const b = path[index + 1]!; const dx = b.x - a.x; const dy = b.y - a.y; const t = Math.max(0, Math.min(1, ((point.x - a.x) * dx + (point.y - a.y) * dy) / (dx * dx + dy * dy || 1))); const candidate = { x: a.x + dx * t, y: a.y + dy * t }; const value = distance(point, candidate); if (value < best.distance) best = { point: candidate, index, distance: value }; } return best; }
function roadWidth(road: DrawingElement) { return routeElementWidthCap(road) ?? Infinity; }
function ribbonWidth(element: DrawingElement, fallback: number) { return routeElementRibbonWidth(element, fallback); }
function intersection(a: Point, b: Point, c: Point, d: Point) { const denominator = (b.x - a.x) * (d.y - c.y) - (b.y - a.y) * (d.x - c.x); if (Math.abs(denominator) < 1e-9) return undefined; const t = ((c.x - a.x) * (d.y - c.y) - (c.y - a.y) * (d.x - c.x)) / denominator; const u = ((c.x - a.x) * (b.y - a.y) - (c.y - a.y) * (b.x - a.x)) / denominator; return t >= 0 && t <= 1 && u >= 0 && u <= 1 ? { x: a.x + t * (b.x - a.x), y: a.y + t * (b.y - a.y) } : undefined; }
function roadAlternative(owner: PlaceNode, roads: Road[], request: StoryRouteRequest, obstacles: PreparedObstacle[], bridges: PreparedRegion[], boundary: PreparedRegion) {
  const width = routeWidth(request); const links = new Map<string, Array<{ id: string; cost: number }>>(); const idOf = (p: Point) => `${p.x.toFixed(6)},${p.y.toFixed(6)}`; const add = (a: Point, b: Point) => { const id = idOf(a); links.set(id, [...(links.get(id) ?? []), { id: idOf(b), cost: distance(a, b) }]); };
  const split = roads.map(({ path }) => path.slice(0, -1).map((point, index) => [point, path[index + 1]!]));
  for (let first = 0; first < roads.length; first += 1) for (let second = first + 1; second < roads.length; second += 1) for (let i = 0; i + 1 < roads[first]!.path.length; i += 1) for (let j = 0; j + 1 < roads[second]!.path.length; j += 1) { const point = intersection(roads[first]!.path[i]!, roads[first]!.path[i + 1]!, roads[second]!.path[j]!, roads[second]!.path[j + 1]!); if (point) { split[first]![i]!.push(point); split[second]![j]!.push(point); } }
  const start = roads.map((road) => ({ road, near: nearestOnPath(request.from.point, road.path) })).toSorted((a, b) => a.near.distance - b.near.distance)[0]; const end = roads.map((road) => ({ road, near: nearestOnPath(request.to.point, road.path) })).toSorted((a, b) => a.near.distance - b.near.distance)[0]; if (!start || !end || start.near.distance > 20 || end.near.distance > 20 || !pointInRegion(request.from.point, boundary.shape) || !pointInRegion(request.to.point, boundary.shape)) return undefined;
  split[roads.indexOf(start.road)]![start.near.index]!.push(start.near.point); split[roads.indexOf(end.road)]![end.near.index]!.push(end.near.point);
  links.clear(); for (let index = 0; index < roads.length; index += 1) for (let segment = 0; segment < split[index]!.length; segment += 1) { const a = roads[index]!.path[segment]!; const points = split[index]![segment]!.toSorted((left, right) => distance(a, left) - distance(a, right)); for (let i = 0; i + 1 < points.length; i += 1) if (openSegment(points[i]!, points[i + 1]!, boundary, obstacles, bridges, width / 2)) { add(points[i]!, points[i + 1]!); add(points[i + 1]!, points[i]!); } }
  const startId = "start"; const endId = "end"; links.set(startId, [{ id: idOf(start.near.point), cost: start.near.distance }]); links.set(idOf(end.near.point), [...(links.get(idOf(end.near.point)) ?? []), { id: endId, cost: end.near.distance }]);
  const values = new Map([[startId, 0]]); const previous = new Map<string, string>(); const seen = new Set<string>(); while (true) { const current = [...values.keys()].filter((id) => !seen.has(id)).toSorted((a, b) => values.get(a)! - values.get(b)! || a.localeCompare(b))[0]; if (!current) break; seen.add(current); if (current === endId) break; for (const edge of links.get(current) ?? []) { const candidate = values.get(current)! + edge.cost; if (candidate < (values.get(edge.id) ?? Infinity)) { values.set(edge.id, candidate); previous.set(edge.id, current); } } }
  if (!values.has(endId)) return undefined; const points: Point[] = [request.to.point]; for (let id = endId; id !== startId;) { const prior = previous.get(id); if (!prior) return undefined; if (prior !== startId) points.unshift({ x: Number(prior.split(",")[0]), y: Number(prior.split(",")[1]) }); id = prior; } points.unshift(request.from.point); return { id: `road-${start.road.element.id}-${end.road.element.id}`, segments: [{ placeId: owner.id, kind: "road" as const, points, sourceId: start.road.element.id }], points, distance: polylineDistance(points), conditions: [], reasons: [], usedOpeningIds: [], usedTransitionIds: [] } satisfies StoryRouteAlternative;
}
export function findOutdoorRoute(project: EditorProject, request: StoryRouteRequest, options: StoryRouteOptions = {}): StoryRouteAlternative | undefined {
  const owner = project.places.find(({ id }) => id === request.from.placeId); if (!owner || request.to.placeId !== owner.id || !accessAllowed(project, owner, request, options)) return undefined;
  const obstacles: Obstacle[] = []; for (const place of project.places.filter(({ kind, id, boundary }) => kind === "building" && id !== owner.id && Boolean(boundary)).toSorted(({ id: first }, { id: second }) => first.localeCompare(second))) obstacles.push({ id: place.id, shape: transformRegion(relativePlaceMatrix(project, owner.id, place.id), place.boundary!) });
  for (const element of project.elements.toSorted(({ id: first }, { id: second }) => first.localeCompare(second))) {
    const { water, barrier } = outdoorElementSemantics(element); if (!barrier) continue;
    const ownerId = project.places.some(({ id }) => id === element.belongsToId) ? element.belongsToId : owner.id; const matrix = relativePlaceMatrix(project, owner.id, ownerId);
    if (element.geometry.kind === "region") obstacles.push({ id: element.id, shape: transformRegion(matrix, element.geometry.shape), water });
    else if (water && (element.geometry.kind === "path" || element.geometry.kind === "bezier")) { const path = transformedPath(project, owner.id, element); const shape = ribbonShape(path, ribbonWidth(element, routeWidth(request))); if (shape) obstacles.push({ id: element.id, shape, water: true }); }
  }
  const bridges = project.elements.filter((element) => outdoorElementSemantics(element).bridge).toSorted(({ id: first }, { id: second }) => first.localeCompare(second)).map((element) => { const ownerId = project.places.some(({ id }) => id === element.belongsToId) ? element.belongsToId : owner.id; return transformRegion(relativePlaceMatrix(project, owner.id, ownerId), (element.geometry as Extract<DrawingElement["geometry"], { kind: "region" }>).shape); });
  const boundary = bounds(owner, request, obstacles); const preparedBoundary = preparedRegion(boundary); const preparedObstacles = obstacles.map((obstacle) => ({ ...obstacle, ...preparedRegion(obstacle.shape) })); const preparedBridges = bridges.map(preparedRegion); const roads: Road[] = project.elements.filter(({ belongsToId, layerId, geometry }) => layerId === "roads" && (geometry.kind === "path" || geometry.kind === "bezier") && (belongsToId === owner.id || project.places.some(({ id, parentId }) => id === belongsToId && parentId === owner.id))).toSorted(({ id: first }, { id: second }) => first.localeCompare(second)).map((element) => ({ element, path: transformedPath(project, owner.id, element) })).filter(({ element, path }) => { if (path.length < 2 || roadWidth(element) + 1e-7 < routeWidth(request)) return false; const custom = options.access?.({ kind: "road", id: element.id, scopeId: element.belongsToId, access: element.access, locked: false }, { actorId: request.actorId, scenarioId: request.scenarioId, stepId: request.stepId }); const access = custom ?? storyAccessDecision(project, { kind: "road", id: element.id, scopeId: element.belongsToId }, { actorId: request.actorId, scenarioId: request.scenarioId, stepId: request.stepId }); return access === true || typeof access !== "boolean" && access.allowed; });
  const preferRoads = request.preferences?.preferRoads ?? true; if (preferRoads) { const road = roadAlternative(owner, roads, request, preparedObstacles, preparedBridges, preparedBoundary); if (road) return road; if (request.preferences?.allowOffroad === false) return undefined; } if (request.preferences?.allowOffroad === false) return undefined;
  const route = visibility(preparedBoundary, preparedObstacles, preparedBridges, request.from.point, request.to.point, candidatePoints(boundary, obstacles, bridges, roads, routeWidth(request) + .1), routeWidth(request) / 2); if (!route) return undefined; return { id: "offroad-direct", segments: [{ placeId: owner.id, kind: "outdoor" as const, points: route.points }], points: route.points, distance: route.distance, conditions: [], reasons: [], usedOpeningIds: [], usedTransitionIds: [] } satisfies StoryRouteAlternative;
}
