"use client";

import type { StoryCopy, StoryRecord, StoryViewState } from "./story-types";
import styles from "./story-workbench.module.css";

export type StoryTopBarProps = { copy: StoryCopy; view: StoryViewState; lenses: StoryRecord[]; scenarios: StoryRecord[]; steps?: StoryRecord[]; routes: StoryRecord[]; onChange(patch: Partial<StoryViewState>): void; onScenario(id: string): void; onStep?(id: string | undefined): void; onRouteSelected?: (routeId: string | undefined) => void };

export function StoryTopBar({ copy, view, lenses, scenarios, steps = [], routes, onChange, onScenario, onStep, onRouteSelected }: StoryTopBarProps) {
  const neutral = !view.activeLensId && !view.activeScenarioId && !view.activeRouteId;
  return <section className={styles.storyStrip} aria-label={`${copy.active} ${copy.context}`}><label>{copy.lenses}<select value={view.activeLensId ?? ""} onChange={(event) => onChange({ activeLensId: event.currentTarget.value || undefined })}><option value="">{copy.neutral}</option>{lenses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{copy.scenario}<select value={view.activeScenarioId ?? ""} onChange={(event) => onScenario(event.currentTarget.value)}><option value="">{copy.noScenario}</option>{scenarios.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{view.activeScenarioId && <fieldset className={styles.contextMode}><legend>{copy.scenario}</legend><button type="button" aria-pressed={view.scenarioContext === "base"} className={view.scenarioContext === "base" ? styles.isActive : undefined} onClick={() => onChange({ scenarioContext: "base", activeStepId: undefined })}>{copy.editBase}</button><button type="button" aria-pressed={view.scenarioContext === "active"} className={view.scenarioContext === "active" ? styles.isActive : undefined} onClick={() => onChange({ scenarioContext: "active" })}>{copy.editScenario}</button></fieldset>}{view.activeScenarioId && steps.length > 0 && <label>{copy.steps}<select value={view.activeStepId ?? ""} onChange={(event) => { const stepId = event.currentTarget.value || undefined; onChange({ activeStepId: stepId, scenarioContext: "active" }); onStep?.(stepId); }}><option value="">{copy.wholeScenario}</option>{steps.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>{copy.route}<select value={view.activeRouteId ?? ""} onChange={(event) => { const routeId = event.currentTarget.value || undefined; onChange({ activeRouteId: routeId }); onRouteSelected?.(routeId); }}><option value="">{copy.neutral}</option>{routes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="button" className={neutral ? styles.isActive : undefined} aria-pressed={neutral} onClick={() => { onChange({ activeLensId: undefined, activeScenarioId: undefined, activeStepId: undefined, activeRouteId: undefined, scenarioContext: "base" }); onRouteSelected?.(undefined); }}>{copy.allNeutral}</button></section>;
}
