import type { EditorProject } from "../model/project-model";
import { renderProjectViewSvg, type ProjectRenderOptions } from "./project-renderer";
export type ProjectViewExportFormat = "svg" | "png" | "pdf";
function safeName(value: string) { return value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "spatial-project"; }
function download(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }
export function projectViewExportName(project: EditorProject, format: ProjectViewExportFormat) { return `${safeName(project.name)}-view.${format}`; }
export function exportProjectViewSvg(options: ProjectRenderOptions) { const svg = renderProjectViewSvg(options); download(new Blob([svg], { type: "image/svg+xml;charset=utf-8" }), projectViewExportName(options.project, "svg")); return svg; }
export async function exportProjectViewPng(options: ProjectRenderOptions) { const svg = renderProjectViewSvg(options); const sourceUrl = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml;charset=utf-8" })); try { const image = new Image(); image.decoding = "async"; image.src = sourceUrl; await image.decode(); const width = options.width ?? 1200; const height = options.height ?? 820; const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height; const context = canvas.getContext("2d"); if (!context) throw new Error("Canvas rendering is unavailable."); context.drawImage(image, 0, 0, width, height); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((value) => value ? resolve(value) : reject(new Error("PNG export failed.")), "image/png")); download(blob, projectViewExportName(options.project, "png")); return blob; } finally { URL.revokeObjectURL(sourceUrl); } }
export async function exportProjectViewPdf(options: ProjectRenderOptions) { const { exportProjectViewPdf } = await import("./project-export-pdf-browser"); return exportProjectViewPdf(options); }
export async function exportProjectView(format: ProjectViewExportFormat, options: ProjectRenderOptions) { if (format === "svg") return exportProjectViewSvg(options); if (format === "png") return exportProjectViewPng(options); return exportProjectViewPdf(options); }
