import type { ConstructionDocument } from "../construction/construction-document";
import type { WallOpening, VerticalTransition } from "../construction/wall-features";
import { constructionNetwork } from "../construction/construction-network";
import { bezierPathData } from "../geometry/bezier-geometry";
import type { KernelPoint } from "../geometry/geometry-types";
import { regionBounds } from "../geometry/region-transform";
import { regionLabelLayout } from "../geometry/region-label-layout";
import { ribbonShape } from "../geometry/ribbon-geometry";
import { isRibbonElement } from "../geometry/ribbon-geometry";
import { ribbonAppearance } from "../geometry/ribbon-style";
import { roadColor } from "../roads/road-style";
import { ribbonWidth } from "../geometry/ribbon-geometry";
import { stairGlyphMarkup } from "../geometry/stair-glyph";
import type { DrawingElement, EditorProject, PlaceNode, RegionShape } from "../model/project-model";
import { constructionPlaceForView, connectedTransitionsForView, elementContextDepth, fitViewportToRegion, matrixAttribute, relativePlaceMatrix, regionPath, surfaceContextDepth, viewportRegion, visiblePlaceGroups } from "../components/map-sheet-geometry";
import { mapLabelWithArea, mapRegionArea, type MapLabelText } from "../geometry/map-area";
import { wrapNoteText } from "../components/map-sheet-shapes";
import { noteCorners, noteDimensions } from "../geometry/note-geometry";
import { defaultElementColor } from "../model/element-appearance";
import { workbenchCopy, type EditorLocale } from "../i18n/workbench-copy";
import { createProjectStoryDisplayNameResolver } from "../story/object-display-name";
import { storyRefKey } from "../story/types";
import { svgId } from "../geometry/svg-id";

type ProjectRenderViewport = { center: KernelPoint; zoom: number; rotation: number };
export type ProjectRenderOptions = { project: EditorProject; activePlaceId?: string; viewport?: ProjectRenderViewport; width?: number; height?: number; padding?: number; includeContext?: boolean; title?: string; locale?: EditorLocale };
const palette = { paper: "#e8d9b4", ink: "#293a33", mutedInk: "#526055", gold: "#92733f", place: "#d8cfaa", placeStroke: "#2f473c", terrain: "#829664", water: "#70a9bb", equipment: "#9f805b", construction: "#8b9f7d", opening: "#9d493e" } as const;
function safeText(value: unknown, max = 500) { return String(value ?? "").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "").slice(0, max); }
function escapeXml(value: unknown) { return safeText(value).replace(/[<>&"']/g, (character) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" })[character]!); }
function safeColor(value: unknown, fallback: string) { return typeof value === "string" && (/^#[0-9a-f]{3,8}$/i.test(value) || /^[a-z]+$/i.test(value)) ? value : fallback; }
function number(value: unknown, fallback: number, min = 0, max = 10_000) { return typeof value === "number" && Number.isFinite(value) ? Math.max(min, Math.min(max, value)) : fallback; }
function shapeCenter(shape: RegionShape): KernelPoint { const bounds = regionBounds(shape); return { x: (bounds.minX + bounds.maxX) / 2, y: (bounds.minY + bounds.maxY) / 2 }; }
function pointsPath(points: readonly KernelPoint[], closed: boolean) { return points.length ? `M ${points.map(({ x, y }) => `${x} ${y}`).join(" L ")}${closed ? " Z" : ""}` : ""; }
function regionMarkup(shape: RegionShape, fill: string, stroke: string, opacity: number, strokeWidth = 1.4, zoom = 1) { return `<path d="${regionPath(shape)}" fill="${fill}" fill-opacity="${opacity}" stroke="${stroke}" stroke-width="${strokeWidth / Math.max(.0001, zoom)}" fill-rule="evenodd" stroke-linejoin="round"/>`; }
function labelMarkup(text: MapLabelText, shape: RegionShape, zoom: number, id: string, boundaryFallback = false) {
  const label = regionLabelLayout(text, shape, zoom, boundaryFallback); if (!label) return "";
  if (label.kind === "boundary") return `<defs><path id="${id}-label-path" d="${label.path}"/></defs><text fill="${palette.ink}" font-family="Georgia,serif" font-size="${label.fontSize}" font-style="italic" text-anchor="middle" textLength="${label.textLength}" lengthAdjust="spacing" paint-order="stroke" stroke="${palette.paper}" stroke-width="${label.fontSize * .12}"><textPath href="#${id}-label-path" startOffset="50%">${escapeXml(label.text)}</textPath></text>`;
  const rotate = label.rotation ? ` transform="rotate(${label.rotation} ${label.x} ${label.y})"` : "";
  return `<defs><clipPath id="${id}-label-clip"><path d="${regionPath(shape)}" fill-rule="evenodd"/></clipPath></defs><g clip-path="url(#${id}-label-clip)"><text x="${label.x}" y="${label.y + (label.nameOffsetY ?? 0)}" fill="${palette.ink}" font-family="Georgia,serif" font-size="${label.fontSize}" text-anchor="middle" dominant-baseline="middle" textLength="${label.textLength}" lengthAdjust="spacing" paint-order="stroke" stroke="${palette.paper}" stroke-width="${label.fontSize * .12}"${rotate}>${escapeXml(label.text)}</text>${label.secondaryLine ? `<text x="${label.x}" y="${label.y + label.secondaryLine.offsetY}" fill="${palette.ink}" font-family="Georgia,serif" text-anchor="middle" dominant-baseline="middle" font-size="${label.secondaryLine.fontSize}" textLength="${label.secondaryLine.textLength}" lengthAdjust="spacing"${rotate}>${escapeXml(label.secondaryLine.text)}</text>` : ""}</g>`;
}
function placeMarkup(place: PlaceNode, mode: "active" | "child" | "context" | "descendant", transform: string | undefined, zoom: number, units: "metric" | "imperial", showArea: boolean) {
  if (!place.boundary || place.visible === false) return ""; const context = mode === "context" || mode === "descendant"; const fill = safeColor(place.appearance?.fillColor, palette.place); const opacity = number(place.appearance?.fillOpacity, context ? .18 : .38, 0, 1); const label = mapLabelWithArea(place.name, mapRegionArea(place.boundary), units, showArea);
  const showLabel = mode === "child" || mode === "descendant" || mode === "context" && place.kind === "room";
  return `<g${transform ? ` transform="${transform}"` : ""} opacity="${context ? .52 : 1}" aria-label="${escapeXml(place.name)}">${regionMarkup(place.boundary, fill, place.kind === "world" ? palette.gold : palette.placeStroke, opacity, context ? 1 : 1.8, zoom)}${showLabel ? labelMarkup(label, place.boundary, zoom, `place-${svgId(place.id)}`, place.kind === "location" || place.kind === "custom") : ""}</g>`;
}
function elementColor(element: DrawingElement) { if (element.appearance?.fillColor) return safeColor(element.appearance.fillColor, palette.equipment); if (element.layerId === "roads") return roadColor(element.subjectId); const fallback = element.layerId === "terrain" ? palette.terrain : (element.layerId as string) === "construction" ? palette.construction : palette.equipment; return defaultElementColor(element.subjectId.toLowerCase(), fallback); }
function elementLabelShape(element: DrawingElement, roadRibbon?: RegionShape): RegionShape | undefined {
  const geometry = element.geometry;
  if (roadRibbon) return roadRibbon;
  if (geometry.kind === "region") return geometry.shape;
  if (geometry.kind === "point") return { kind: "circle", cx: geometry.at.x, cy: geometry.at.y, radius: 8 };
  if (geometry.kind === "note") return { kind: "polygon", points: noteCorners(geometry) };
  const points = geometry.kind === "path" ? geometry.points : geometry.nodes.flatMap(({ anchor, inHandle, outHandle }) => [anchor, ...(inHandle ? [inHandle] : []), ...(outHandle ? [outHandle] : [])]);
  if (!points.length) return undefined;
  const minX = Math.min(...points.map(({ x }) => x)); const maxX = Math.max(...points.map(({ x }) => x)); const minY = Math.min(...points.map(({ y }) => y)); const maxY = Math.max(...points.map(({ y }) => y)); const padding = 3;
  return { kind: "rectangle", x: minX - padding, y: minY - padding, width: Math.max(padding * 2, maxX - minX + padding * 2), height: Math.max(padding * 2, maxY - minY + padding * 2) };
}
function roadMarkup(ribbon: RegionShape, element: DrawingElement) {
  const filterId = `road-soft-${svgId(element.id)}`; const width = ribbonWidth(element); const appearance = ribbonAppearance(element); const path = regionPath(ribbon);
  return `<g opacity="${number(appearance.fillOpacity, .7, 0, 1)}"><defs><filter id="${filterId}" x="-20%" y="-20%" width="140%" height="140%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="${width * .045}"/></filter></defs><path d="${path}" fill="${safeColor(appearance.fillColor, palette.equipment)}" fill-rule="evenodd" filter="url(#${filterId})" pointer-events="none"/><path d="${path}" fill="${safeColor(appearance.fillColor, palette.equipment)}" fill-opacity=".15" fill-rule="evenodd" stroke="none"/></g>`;
}
function elementMarkup(element: DrawingElement, zoom: number, units: "metric" | "imperial", showArea: boolean, transform?: string, contextDepth = 0) {
  if (element.visible === false) return ""; const color = safeColor(element.appearance?.fillColor, elementColor(element)); const opacity = number(element.appearance?.fillOpacity, element.layerId === "sketch" ? .72 : .55, 0, 1); const contextOpacity = contextDepth < 0 ? .42 : contextDepth > 0 ? .68 : 1; const width = number(element.widthMeters ?? element.properties.widthMeters, element.layerId === "roads" ? 2.5 : 1.8, .1, 1000); const geometry = element.geometry; let body = ""; let center: KernelPoint | undefined; let labelShape: RegionShape | undefined;
  if (isRibbonElement(element) && (geometry.kind === "path" || geometry.kind === "bezier")) { const road = { ...element, widthMeters: width }; const ribbon = ribbonShape(road); center = geometry.kind === "path" ? geometry.points[Math.floor(geometry.points.length / 2)] : geometry.nodes[Math.floor(geometry.nodes.length / 2)]?.anchor; labelShape = ribbon; body = ribbon ? roadMarkup(ribbon, road) : ""; }
  else if (geometry.kind === "region") { center = shapeCenter(geometry.shape); labelShape = geometry.shape; body = regionMarkup(geometry.shape, color, color, opacity, 1.2, zoom); }
  else if (geometry.kind === "path") { center = geometry.points[Math.floor(geometry.points.length / 2)]; labelShape = elementLabelShape(element); body = `<path d="${pointsPath(geometry.points, geometry.closed)}" fill="none" stroke="${color}" stroke-opacity="${opacity}" stroke-width="${width / Math.max(.0001, zoom)}" stroke-linecap="round" stroke-linejoin="round"/>`; }
  else if (geometry.kind === "bezier") { center = geometry.nodes[Math.floor(geometry.nodes.length / 2)]?.anchor; labelShape = elementLabelShape(element); body = `<path d="${bezierPathData(geometry.nodes, geometry.closed)}" fill="none" stroke="${color}" stroke-opacity="${opacity}" stroke-width="${width / Math.max(.0001, zoom)}" stroke-linecap="round" stroke-linejoin="round"/>`; }
  else if (geometry.kind === "point") { center = geometry.at; labelShape = elementLabelShape(element); body = `<circle cx="${center.x}" cy="${center.y}" r="${number(element.properties.markerSize, 3, .5, 40) / Math.max(.0001, zoom)}" fill="${color}" fill-opacity="${opacity}" stroke="${palette.paper}" stroke-width="${1 / Math.max(.0001, zoom)}"/>`; }
  else { const noteCenter = geometry.at; center = noteCenter; const { width: noteWidth, height: noteHeight } = noteDimensions(geometry); const fontSize = number(element.properties.fontSize, Math.min(14, Math.max(7, noteHeight * .22)), 1, 100) / Math.max(.0001, zoom); const lineHeight = fontSize * 1.25; const lines = wrapNoteText(safeText(geometry.text), noteWidth, fontSize); const maxLines = Math.max(1, Math.floor((noteHeight - fontSize * .35) / lineHeight)); const visibleLines = lines.length > maxLines ? [...lines.slice(0, maxLines - 1), `${lines[maxLines - 1]}…`] : lines; const textMarkup = visibleLines.map((line, index) => `<tspan x="${noteCenter.x + fontSize * .45}" dy="${index ? lineHeight : 0}">${escapeXml(line || " ")}</tspan>`).join(""); const rotate = geometry.rotation ? ` transform="rotate(${geometry.rotation} ${noteCenter.x} ${noteCenter.y})"` : ""; body = `<g${rotate}><rect x="${noteCenter.x}" y="${noteCenter.y}" width="${noteWidth}" height="${noteHeight}" rx="${1.5 / Math.max(.0001, zoom)}" fill="${palette.paper}" fill-opacity=".22" stroke="${palette.gold}" stroke-dasharray="2 2"/><text x="${noteCenter.x + fontSize * .45}" y="${noteCenter.y + fontSize}" fill="${palette.ink}" font-family="Georgia,serif" font-size="${fontSize}">${textMarkup}</text></g>`; labelShape = elementLabelShape(element); }
  const label = center && geometry.kind !== "note" && labelShape ? labelMarkup(mapLabelWithArea(element.name, mapRegionArea(labelShape), units, showArea), labelShape, zoom, `element-${svgId(element.id)}`) : "";
  return `<g${transform ? ` transform="${transform}"` : ""} opacity="${contextOpacity}" aria-label="${escapeXml(element.name)}">${body}${label}</g>`;
}
function openingMarkup(document: ConstructionDocument, opening: WallOpening, zoom: number) {
  const wall = document.walls.find(({ id }) => id === opening.wallId); if (!wall) return ""; const x = wall.start.x + (wall.end.x - wall.start.x) * opening.position; const y = wall.start.y + (wall.end.y - wall.start.y) * opening.position; const angle = Math.atan2(wall.end.y - wall.start.y, wall.end.x - wall.start.x) * 180 / Math.PI; const half = opening.width / 2; const depth = Math.max(.14, wall.thickness * .8); const stroke = 1.2 / Math.max(.0001, zoom); const clearStroke = Math.max(1, wall.thickness * 2) / Math.max(.0001, zoom); const mark = opening.kind === "window" ? `<line x1="${-half}" y1="${-depth * .55}" x2="${half}" y2="${-depth * .55}"/><line x1="${-half}" y1="${depth * .55}" x2="${half}" y2="${depth * .55}"/>` : opening.kind === "passage" ? `<path d="M ${-half} ${-depth * .6} L ${half} ${-depth * .6} M ${-half} ${depth * .6} L ${half} ${depth * .6}"/>` : `<line x1="${-half}" y1="0" x2="${-half}" y2="${opening.kind === "gate" ? -half : -opening.width}"/><path d="M ${half} 0 A ${opening.kind === "gate" ? half : opening.width} ${opening.kind === "gate" ? half : opening.width} 0 0 0 ${-half} ${opening.kind === "gate" ? -half : -opening.width}"/>`; return `<g transform="translate(${x} ${y}) rotate(${angle})" fill="none" stroke="${palette.opening}" stroke-width="${stroke}"><line x1="${-half}" y1="0" x2="${half}" y2="0" stroke="${palette.paper}" stroke-width="${clearStroke}"/><line x1="${-half}" y1="${-depth}" x2="${-half}" y2="${depth}"/><line x1="${half}" y1="${-depth}" x2="${half}" y2="${depth}"/>${mark}</g>`;
}
type TransitionDisplayName = (transition: VerticalTransition, scopeId: string) => string;

function createTransitionDisplayName(project: EditorProject, locale: EditorLocale): TransitionDisplayName {
  const copy = workbenchCopy[locale].objectList;
  const names = createProjectStoryDisplayNameResolver(project, copy);
  const labels = new Map<string, string>();
  for (const construction of project.constructions) construction.transitions.forEach((transition, index) => {
    const ref = { kind: "transition" as const, id: transition.id, scopeId: construction.id };
    const fallback = transition.kind === "elevator" ? copy.elevatorName?.(index + 1) ?? copy.stairsName(index + 1) : copy.stairsName(index + 1);
    labels.set(storyRefKey(ref), names.label(ref, fallback));
  });
  return (transition, scopeId) => labels.get(storyRefKey({ kind: "transition", id: transition.id, scopeId }))
    ?? (transition.kind === "elevator" ? copy.elevatorName?.(1) ?? copy.stairsName(1) : copy.stairsName(1));
}

function constructionMarkup(project: EditorProject, document: ConstructionDocument, zoom: number, units: "metric" | "imperial", showArea: boolean, transitionName: TransitionDisplayName, transform?: string) {
  const network = constructionNetwork(document.walls, document.enclosure); const rooms = network.faces.map((face) => { const room = document.rooms.find(({ faceId }) => faceId === face.id); const roomPlace = room && project.places.find(({ id }) => id === room.id); if (room?.visible === false || roomPlace?.visible === false) return ""; const shape: RegionShape = { kind: "compound", polygons: [{ outer: face.outer, holes: face.holes }] }; const appearance = roomPlace?.appearance; const roomName = mapLabelWithArea(room?.name ?? "Room", mapRegionArea(shape), units, showArea); return `<g aria-label="${escapeXml(room?.name ?? "Room")}"><path d="${pointsPath(face.outer, true)} ${face.holes.map((hole) => pointsPath(hole, true)).join(" ")}" fill="${safeColor(appearance?.fillColor, palette.construction)}" fill-opacity="${number(appearance?.fillOpacity, .2, 0, 1)}" fill-rule="evenodd"/>${room ? labelMarkup(roomName, shape, zoom, `room-${svgId(document.id)}-${svgId(room.id)}`) : ""}</g>`; }).join(""); const enclosure = document.enclosure ? regionMarkup(document.enclosure, palette.place, palette.placeStroke, .1, 1.8, zoom) : ""; const walls = document.walls.filter(({ visible }) => visible !== false).map((wall) => `<path d="M ${wall.start.x} ${wall.start.y} L ${wall.end.x} ${wall.end.y}" fill="none" stroke="${wall.role === "partition" ? palette.mutedInk : palette.ink}" stroke-width="${(wall.role === "boundary" ? 3.4 : wall.thickness * 2) / Math.max(.0001, zoom)}" stroke-linecap="square"/>`).join(""); const openings = document.openings.filter(({ visible }) => visible !== false).map((opening) => openingMarkup(document, opening, zoom)).join(""); const transitions = document.transitions.filter(({ visible }) => visible !== false).map((transition) => transitionMarkup(transition, document.id, zoom, transitionName(transition, document.id))).join(""); return `<g${transform ? ` transform="${transform}"` : ""} aria-label="Construction">${enclosure}${rooms}${walls}${openings}${transitions}</g>`;
}
function transitionMarkup(transition: VerticalTransition, scopeId: string, zoom: number, displayName: string, transform?: string) { const id = `transition-${svgId(scopeId)}-${svgId(transition.id)}`; const bounds = regionBounds(transition.footprint); const glyph = transition.kind === "stairs" ? `<defs><clipPath id="${id}-clip"><path d="${regionPath(transition.footprint)}"/></clipPath></defs><g clip-path="url(#${id}-clip)"${transition.direction ? ` transform="rotate(${transition.direction} ${(bounds.minX + bounds.maxX) / 2} ${(bounds.minY + bounds.maxY) / 2})"` : ""}>${stairGlyphMarkup(transition.style ?? "straight", bounds, zoom)}</g>` : ""; return `<g${transform ? ` transform="${transform}"` : ""} aria-label="${escapeXml(displayName)}">${regionMarkup(transition.footprint, transition.kind === "elevator" ? palette.equipment : palette.construction, palette.mutedInk, .22, 1.2, zoom)}${glyph}${labelMarkup(displayName, transition.footprint, zoom, id)}</g>`; }
function transformedBounds(shape: RegionShape, matrix?: ReturnType<typeof relativePlaceMatrix>) {
  const bounds = regionBounds(shape); const corners = [{ x: bounds.minX, y: bounds.minY }, { x: bounds.maxX, y: bounds.minY }, { x: bounds.maxX, y: bounds.maxY }, { x: bounds.minX, y: bounds.maxY }];
  return corners.map((point) => matrix ? { x: matrix[0] * point.x + matrix[2] * point.y + matrix[4], y: matrix[1] * point.x + matrix[3] * point.y + matrix[5] } : point);
}
function elementShape(element: DrawingElement): RegionShape | undefined {
  const geometry = element.geometry;
  if (isRibbonElement(element) && (geometry.kind === "path" || geometry.kind === "bezier")) return ribbonShape(element);
  if (geometry.kind === "region") return geometry.shape;
  if (geometry.kind === "point") return { kind: "circle", cx: geometry.at.x, cy: geometry.at.y, radius: 3 };
  if (geometry.kind === "note") return { kind: "polygon", points: noteCorners(geometry) };
  const points = geometry.kind === "path" ? geometry.points : geometry.nodes.flatMap(({ anchor, inHandle, outHandle }) => [anchor, ...(inHandle ? [inHandle] : []), ...(outHandle ? [outHandle] : [])]);
  return points.length ? { kind: "polygon", points } : undefined;
}
function projectFitRegion(project: EditorProject, targetId?: string, includeContext = true): RegionShape | undefined {
  const points: KernelPoint[] = []; const add = (shape: RegionShape | undefined, ownerId?: string) => { if (!shape) return; try { points.push(...transformedBounds(shape, targetId && ownerId && ownerId !== targetId ? relativePlaceMatrix(project, targetId, ownerId) : undefined)); } catch { /* malformed untrusted ownership is ignored by the file parser */ } };
  if (targetId) {
    const groups = visiblePlaceGroups(project, targetId); const places = [...(includeContext ? groups.context : []), ...(groups.active ? [groups.active] : []), ...groups.children, ...groups.descendants]; places.forEach((place) => place.visible !== false && add(place.boundary, place.id));
    project.elements.forEach((element) => { const depth = elementContextDepth(project, targetId, element); if (element.visible !== false && depth !== undefined && (includeContext || depth >= 0)) add(elementShape(element), element.belongsToId); });
    project.surfaces.forEach((surface) => { const depth = surfaceContextDepth(project, targetId, surface); if (surface.visible !== false && depth !== undefined && (includeContext || depth >= 0)) add(surface.shape, surface.belongsToId); });
  } else project.places.forEach((place) => place.visible !== false && add(place.boundary, place.id));
  if (!points.length) return; const minX = Math.min(...points.map(({ x }) => x)); const maxX = Math.max(...points.map(({ x }) => x)); const minY = Math.min(...points.map(({ y }) => y)); const maxY = Math.max(...points.map(({ y }) => y)); return { kind: "rectangle", x: minX, y: minY, width: Math.max(.001, maxX - minX), height: Math.max(.001, maxY - minY) };
}
export function renderProjectViewSvg(options: ProjectRenderOptions) {
  const width = number(options.width, 1200, 32, 20_000); const height = number(options.height, 820, 32, 20_000); const activeId = options.activePlaceId; const targetId = activeId ?? options.project.places.find(({ parentId }) => !parentId)?.id; const active = activeId ? options.project.places.find(({ id }) => id === activeId) : undefined; const groups = activeId ? visiblePlaceGroups(options.project, activeId) : undefined; const showArea = options.project.measureSettings.showRoomAreas; const units = options.project.measureSettings.units; const includeContext = options.includeContext ?? true; const viewport = options.viewport ?? fitViewportToRegion(projectFitRegion(options.project, targetId, includeContext) ?? (activeId ? viewportRegion(options.project, activeId) : undefined), { width, height }, options.padding ?? .16); const mapTransform = `translate(${width / 2} ${height / 2}) rotate(${number(viewport.rotation, 0, -360, 360)}) scale(${number(viewport.zoom, 1, .0001, 100_000)}) translate(${-viewport.center.x} ${-viewport.center.y})`;
  const transitionName = createTransitionDisplayName(options.project, options.locale ?? "en");
  const placeEntries = activeId ? [...(includeContext ? groups!.context.filter(({ kind }) => kind !== "level").map((place) => [place, "context" as const, matrixAttribute(relativePlaceMatrix(options.project, activeId, place.id))] as const) : []), ...(groups!.active ? [[groups!.active, "active" as const, undefined] as const] : []), ...groups!.children.filter(({ kind }) => kind !== "room" && !(groups!.active?.kind === "building" && kind === "level")).map((place) => [place, "child" as const, matrixAttribute(relativePlaceMatrix(options.project, activeId, place.id))] as const), ...groups!.descendants.map((place) => [place, "descendant" as const, matrixAttribute(relativePlaceMatrix(options.project, activeId, place.id))] as const)] : options.project.places.map((place) => [place, place.parentId ? "descendant" as const : "active" as const, targetId && place.id !== targetId ? matrixAttribute(relativePlaceMatrix(options.project, targetId, place.id)) : undefined] as const);
  const places = placeEntries.map(([place, mode, matrix]) => placeMarkup(place, mode, matrix, viewport.zoom, units, showArea)).join("");
  const elements = options.project.elements.flatMap((element) => { const depth = activeId ? elementContextDepth(options.project, activeId, element) : 0; if (element.visible === false || depth === undefined || !includeContext && depth < 0) return []; const matrix = activeId && depth !== 0 ? matrixAttribute(relativePlaceMatrix(options.project, activeId, element.belongsToId)) : !activeId && targetId && element.belongsToId !== targetId ? matrixAttribute(relativePlaceMatrix(options.project, targetId, element.belongsToId)) : undefined; return [elementMarkup(element, viewport.zoom, units, showArea, matrix, depth)]; }).join("");
  const surfaces = options.project.surfaces.flatMap((surface) => { const depth = activeId ? surfaceContextDepth(options.project, activeId, surface) : 0; if (surface.visible === false || depth === undefined) return []; const matrix = activeId && depth !== 0 ? matrixAttribute(relativePlaceMatrix(options.project, activeId, surface.belongsToId)) : !activeId && targetId && surface.belongsToId !== targetId ? matrixAttribute(relativePlaceMatrix(options.project, targetId, surface.belongsToId)) : undefined; return [`<g${matrix ? ` transform="${matrix}"` : ""} aria-label="${escapeXml(surface.name)}">${regionMarkup(surface.shape, safeColor(surface.appearance?.fillColor, palette.equipment), palette.gold, number(surface.appearance?.fillOpacity, .3, 0, 1), 1.2)}${labelMarkup(mapLabelWithArea(surface.name, mapRegionArea(surface.shape), units, showArea), surface.shape, viewport.zoom, `surface-${svgId(surface.id)}`)}</g>`]; }).join("");
  const constructionOwner = activeId ? constructionPlaceForView(options.project, activeId) : undefined; const constructionDocs = constructionOwner?.constructionId ? options.project.constructions.filter(({ id }) => id === constructionOwner.constructionId).map((document) => constructionMarkup(options.project, document, viewport.zoom, units, showArea, transitionName, constructionOwner.id === activeId ? undefined : matrixAttribute(relativePlaceMatrix(options.project, activeId!, constructionOwner.id)))).join("") : !activeId ? options.project.constructions.flatMap((document) => { const owner = options.project.places.find(({ constructionId }) => constructionId === document.id); return owner ? [constructionMarkup(options.project, document, viewport.zoom, units, showArea, transitionName, targetId && owner.id !== targetId ? matrixAttribute(relativePlaceMatrix(options.project, targetId, owner.id)) : undefined)] : []; }).join("") : "";
  const transitions = activeId && constructionOwner && includeContext ? connectedTransitionsForView(options.project, activeId, constructionOwner.constructionId).map(({ transition, scopeId, transform }) => transitionMarkup(transition, scopeId, viewport.zoom, transitionName(transition, scopeId), transform ? matrixAttribute(transform) : undefined)).join("") : ""; const title = options.title ?? [options.project.name, active?.name].filter(Boolean).join(" · "); return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeXml(title)}"><rect width="100%" height="100%" fill="${palette.paper}"/><g transform="${mapTransform}">${places}${constructionDocs}${transitions}${surfaces}${elements}</g><text x="18" y="26" fill="${palette.ink}" font-family="Georgia,serif" font-size="15">${escapeXml(title)}</text></svg>`;
}
export function projectThumbnailSvg(project: EditorProject, options: Pick<ProjectRenderOptions, "width" | "height"> = {}) { const worldId = project.places.find(({ parentId }) => !parentId)?.id; return renderProjectViewSvg({ project, activePlaceId: worldId, width: options.width ?? 320, height: options.height ?? 190, includeContext: false, title: project.name }); }
export function projectThumbnailDataUri(project: EditorProject, options: Pick<ProjectRenderOptions, "width" | "height"> = {}) { return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(projectThumbnailSvg(project, options))}`; }
