import { buildRoadEdit, buildRoadJoin, roadEditingHandles } from "./agent-road-command";
import { buildFlowingWaterJoin, buildRibbonEdit, ribbonEditingHandles } from "./agent-ribbon-command";
import type { EditorSession } from "../state/editor-session";
import type { ProjectCheckpoint, ProjectCheckpointSummary } from "../persistence/project-checkpoint";
import { assertProposalCurrent } from "../persistence/project-checkpoint";
import { buildDrawingChange } from "./agent-drawing-command";
import { buildClearLayerChange, buildHierarchyChange, type HierarchyChange } from "./agent-hierarchy-command";
import { buildCutoutChange, buildDeleteChange, buildDuplicateChange, buildMergeChange, buildMetadataChange, buildResizeChange, buildTransformChange, buildWallEndpointChange } from "./agent-object-command";
import { buildPlanningAlignmentChange, buildPlanningSplitChange } from "./agent-planning-command";
import { addRegionToOutline } from "../drawing/add-to-outline-operation";
import { defaultMeasureSettings, type EditorProject, type ProjectMeasureSettings } from "../model/project-model";
import type { AgentDrawingInput, AgentMetadata, AgentObjectRef, AgentTransformation, AgentTransitionDetails } from "./agent-command-types";
import { EditorCommandCoordinator, projectDiff, type CommandBridge } from "./editor-command-coordinator";
import { constructionClearCategories, drawingSchema, layers, metadataProperties, objectRefSchema, pointSchema, preparedTokenSchema, regionShapeSchema, transitionProperties } from "./agent-tool-schemas";
import { records, refs, regionShape, text } from "./agent-tool-input";
import { projectRevision } from "../state/project-revision";

export type EditorAgentBridge = CommandBridge & {
  getSession(): EditorSession;
  getActivePlaceId(): string;
  refresh(): void;
  openPlace?(placeId: string): boolean;
  focusObjects?(refs: AgentObjectRef[]): boolean | void;
  clearFocus?(): void;
  getCheckpoints?(): ProjectCheckpointSummary[];
  getCheckpoint?(id: string): Promise<ProjectCheckpoint | undefined>;
  createCheckpoint?(name: string): Promise<ProjectCheckpoint | undefined>;
  deleteCheckpoint?(checkpointId: string): Promise<boolean>;
  showCheckpoint?(checkpointId: string | undefined, opacity?: number): boolean;
};

const response = <T,>(value: T) => ({ content: [{ type: "text", text: JSON.stringify(value) }], structuredContent: value });
const mutating = { readOnlyHint: false };
const refsSchema = { type: "array", minItems: 1, items: objectRefSchema };

function metadata(input: Record<string, unknown>): AgentMetadata {
  return {
    ...(typeof input.name === "string" ? { name: input.name } : {}), ...(typeof input.description === "string" ? { description: input.description } : {}),
    ...(Array.isArray(input.tags) ? { tags: input.tags as string[] } : {}), ...(input.appearance && typeof input.appearance === "object" ? { appearance: input.appearance as AgentMetadata["appearance"] } : {}),
    ...(typeof input.visible === "boolean" ? { visible: input.visible } : {}), ...(typeof input.locked === "boolean" ? { locked: input.locked } : {}),
  };
}

function prepare(coordinator: EditorCommandCoordinator, id: string, build: Parameters<EditorCommandCoordinator["prepare"]>[1]) {
  return response(coordinator.prepare(`agent:${id}:${crypto.randomUUID()}`, build));
}

async function fullCheckpoint(bridge: EditorAgentBridge, id: string) {
  const listed = bridge.getCheckpoints?.().find((item) => item.id === id);
  if (!listed) return undefined;
  return bridge.getCheckpoint ? bridge.getCheckpoint(id) : "snapshot" in listed ? listed as ProjectCheckpoint : undefined;
}

function hierarchyInput(input: Record<string, unknown>): HierarchyChange {
  const action = text(input, "action") as HierarchyChange["action"];
  if (action === "add-map-level") return { action, placeId: text(input, "placeId"), kind: text(input, "kind") as "world", name: input.name as string | undefined, locale: input.locale as "pl" | "en" | undefined };
  if (action === "add-building-level") return { action, buildingId: text(input, "buildingId"), position: text(input, "position") as "above" | "below", name: input.name as string | undefined };
  if (action === "reorder-level") return { action, levelId: text(input, "levelId"), beforeLevelId: input.beforeLevelId as string | undefined };
  if (action === "reparent-place") return { action, placeId: text(input, "placeId"), parentId: input.parentId as string | undefined };
  throw new TypeError("unknown hierarchy action");
}

function measureSettings(input: unknown): Partial<ProjectMeasureSettings> {
  if (!input || typeof input !== "object" || Array.isArray(input)) throw new TypeError("measureSettings must be an object");
  const candidate = input as Record<string, unknown>; const next: Partial<ProjectMeasureSettings> = {};
  if (candidate.units === "metric" || candidate.units === "imperial") next.units = candidate.units;
  else if (candidate.units !== undefined) throw new TypeError("measureSettings.units must be metric or imperial");
  for (const key of ["gridVisible", "showAxes", "snapToGrid", "showRoomAreas"] as const) if (candidate[key] !== undefined) { if (typeof candidate[key] !== "boolean") throw new TypeError(`measureSettings.${key} must be boolean`); next[key] = candidate[key]; }
  for (const key of ["gridOpacity", "gridSpacingMeters", "pencilSmoothing"] as const) if (candidate[key] !== undefined) { if (typeof candidate[key] !== "number" || !Number.isFinite(candidate[key])) throw new TypeError(`measureSettings.${key} must be finite`); next[key] = candidate[key]; }
  if (next.gridOpacity !== undefined && (next.gridOpacity < 0 || next.gridOpacity > 1)) throw new TypeError("measureSettings.gridOpacity must be between 0 and 1");
  if (next.gridSpacingMeters !== undefined && next.gridSpacingMeters <= 0) throw new TypeError("measureSettings.gridSpacingMeters must be positive");
  if (next.pencilSmoothing !== undefined && (next.pencilSmoothing < 0 || next.pencilSmoothing > 1)) throw new TypeError("measureSettings.pencilSmoothing must be between 0 and 1");
  return next;
}

function projectSettingsChange(project: EditorProject, input: Record<string, unknown>) {
  const hasName = typeof input.name === "string" && input.name.trim().length > 0;
  const hasMeasures = input.measureSettings !== undefined;
  if (!hasName && !hasMeasures) throw new TypeError("name or measureSettings is required");
  const settings = hasMeasures ? { ...defaultMeasureSettings(), ...project.measureSettings, ...measureSettings(input.measureSettings) } : project.measureSettings;
  return { project: { ...project, ...(hasName ? { name: (input.name as string).trim() } : {}), measureSettings: settings }, summary: hasName && hasMeasures ? "Zmieniono ustawienia projektu i pomiarów." : hasName ? "Zmieniono nazwę projektu." : "Zmieniono ustawienia pomiarów.", effects: [`updated:project:${project.id}`] };
}

export function createEditorAgentTools(bridge: EditorAgentBridge, coordinator = new EditorCommandCoordinator(bridge)): WebMcpTool[] {
  const pendingCheckpointDeletes = new Map<string, string>();
  return [
    { name: "inspect_road_handles", title: "Inspect road editing handles", description: "Read road anchors and left/right edge handles in owner-local metres for prepare_edit_road. Read-only.", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"], additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async (input) => response(roadEditingHandles(bridge.getSession().getState().project, text(input, "id"))) },
    { name: "prepare_edit_road", title: "Prepare road width or shape edit", description: "Prepare a road edit: channel 0 moves a path/Bezier anchor, 1 the left edge handle, 2 the right; widthMeters scales the profile. Read exact indices/points first. Preview only; apply token to commit.", inputSchema: { type: "object", properties: { id: { type: "string" }, widthMeters: { type: "number", minimum: .1, maximum: 1000 }, channel: { type: "integer", minimum: 0, maximum: 2 }, index: { type: "integer", minimum: 0 }, point: pointSchema }, required: ["id"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "road", (project) => buildRoadEdit(project, input)) },
    { name: "inspect_ribbon_handles", title: "Inspect river and stream handles", description: "Read road/river/stream centerline and bank handles in owner-local metres for prepare_edit_ribbon. Read-only.", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"], additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async (input) => response(ribbonEditingHandles(bridge.getSession().getState().project, text(input, "id"))) },
    { name: "prepare_edit_ribbon", title: "Prepare river or stream width or shape edit", description: "Prepare a river/stream edit: channel 0 moves an anchor, 1 the left bank, 2 the right; widthMeters scales the profile. Preview only; apply token to commit.", inputSchema: { type: "object", properties: { id: { type: "string" }, widthMeters: { type: "number", minimum: .1, maximum: 1000 }, channel: { type: "integer", minimum: 0, maximum: 2 }, index: { type: "integer", minimum: 0 }, point: pointSchema }, required: ["id"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "ribbon", (project) => buildRibbonEdit(project, input)) },
    { name: "prepare_join_watercourses", title: "Prepare joining rivers or streams", description: "Prepare joining exactly two open rivers/streams at nearby endpoints, preserving profiles, cutout masks, and metadata. Keep the first subject/name. Preview only; apply token to commit.", inputSchema: { type: "object", properties: { refs: { type: "array", minItems: 2, maxItems: 2, items: objectRefSchema } }, required: ["refs"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "join-watercourses", (project) => buildFlowingWaterJoin(project, refs(input))) },
    { name: "prepare_join_roads", title: "Prepare joining two roads", description: "Prepare joining exactly two open roads at nearby endpoints, preserving anchors, profiles, and cutouts. Internal crossings create an editable junction while both roads remain. Preview only; apply token to commit.", inputSchema: { type: "object", properties: { refs: { type: "array", minItems: 2, maxItems: 2, items: objectRefSchema } }, required: ["refs"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "join-roads", (project) => buildRoadJoin(project, refs(input))) },
    { name: "prepare_create_map_object", title: "Prepare a map creation", description: "Prepare road.paved/dirt/path/sidewalk, rivers/streams (widthMeters), terrain, a location boundary, a building with its default level, walls, doors/windows, stairs, equipment, notes, or sketches under editor geometry rules. Points use owner's local floor/map metres; circle=centre+circumference point, rectangle/ellipse=opposite corners. Inspect owner/construction first; the model recentres each owner view from calculated bounds; no change until applied.", inputSchema: drawingSchema, annotations: mutating, execute: async (input) => prepare(coordinator, "draw", (project) => buildDrawingChange(project, bridge.getActivePlaceId(), { ...input, ...metadata(input) } as AgentDrawingInput)) },
    { name: "prepare_update_project_object", title: "Prepare object details or ownership", description: "Prepare changing an object's name, description, tags, color, visibility, lock, ownership, opening width, stair/lift links, or style.", inputSchema: { type: "object", properties: { ref: objectRefSchema, ownerId: { type: "string" }, openingWidth: { type: "number", exclusiveMinimum: 0 }, ...transitionProperties, ...metadataProperties }, required: ["ref"], additionalProperties: false }, annotations: mutating, execute: async (input) => {
      const ref = records({ refs: [input.ref] }, "refs")[0] as unknown as AgentObjectRef;
      const transitionDetails: AgentTransitionDetails | undefined = ref.type === "transition" ? { sourceLevelId: input.sourceLevelId as string | undefined, targetLevelId: input.targetLevelId as string | undefined, connectedLevelIds: input.connectedLevelIds as string[] | undefined, style: input.transitionStyle as AgentTransitionDetails["style"], direction: input.direction as number | undefined, sameLevelRise: input.sameLevelRise as boolean | undefined } : undefined;
      return prepare(coordinator, "metadata", (project) => buildMetadataChange(project, bridge.getActivePlaceId(), { ref, metadata: metadata(input), ownerId: input.ownerId as string | undefined, openingWidth: input.openingWidth as number | undefined, transitionDetails }));
    } },
    { name: "prepare_update_project_settings", title: "Prepare project and view settings", description: "Prepare project name or metric/imperial units, grid/axes, spacing, opacity, snapping, room areas, or pencil smoothing.", inputSchema: { type: "object", properties: { name: { type: "string" }, measureSettings: { type: "object", properties: { units: { type: "string", enum: ["metric", "imperial"] }, gridVisible: { type: "boolean" }, showAxes: { type: "boolean" }, gridOpacity: { type: "number", minimum: 0, maximum: 1 }, gridSpacingMeters: { type: "number", exclusiveMinimum: 0 }, snapToGrid: { type: "boolean" }, showRoomAreas: { type: "boolean" }, pencilSmoothing: { type: "number", minimum: 0, maximum: 1 } }, additionalProperties: false } }, additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "project-settings", (project) => projectSettingsChange(project, input)) },
    { name: "prepare_transform_project_objects", title: "Prepare moving, rotating or mirroring objects", description: "Prepare a precise transformation of one or more places, rooms, walls, openings, stairs, or drawing objects; mixed types may move together.", inputSchema: { type: "object", properties: { refs: refsSchema, transformation: { oneOf: [
      { type: "object", properties: { kind: { const: "move" }, dx: { type: "number" }, dy: { type: "number" } }, required: ["kind", "dx", "dy"], additionalProperties: false },
      { type: "object", properties: { kind: { const: "rotate" }, degrees: { type: "number" } }, required: ["kind", "degrees"], additionalProperties: false },
      { type: "object", properties: { kind: { const: "mirror" }, axis: { type: "string", enum: ["horizontal", "vertical"] } }, required: ["kind", "axis"], additionalProperties: false },
    ] }, boundaryEditing: { type: "boolean" } }, required: ["refs", "transformation"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "transform", (project) => buildTransformChange(project, bridge.getActivePlaceId(), refs(input), input.transformation as AgentTransformation, input.boundaryEditing === true)) },
    { name: "prepare_align_objects", title: "Prepare aligning or distributing objects", description: "Prepare aligning/distributing mixed places, rooms, drawing elements, and construction surfaces in active-map coordinates. distribute=true spaces evenly; otherwise edge=start, center, or end. Preview only; apply token to commit.", inputSchema: { type: "object", properties: { refs: refsSchema, axis: { type: "string", enum: ["horizontal", "vertical"] }, edge: { type: "string", enum: ["start", "center", "end"] }, distribute: { type: "boolean" }, boundaryEditing: { type: "boolean" } }, required: ["refs", "axis"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "align", (project) => buildPlanningAlignmentChange(project, bridge.getActivePlaceId(), { refs: refs(input), axis: input.axis as "horizontal" | "vertical", edge: input.edge as "start" | "center" | "end" | undefined, distribute: input.distribute === true, boundaryEditing: input.boundaryEditing === true })) },
    { name: "prepare_split_path", title: "Prepare splitting a path at a node", description: "Prepare splitting an open path/Bezier at a selected interior node; roads retain profiles and cutout masks. Preview only; apply token to commit.", inputSchema: { type: "object", properties: { ref: objectRefSchema, vertexIndex: { type: "integer", minimum: 1 } }, required: ["ref", "vertexIndex"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "split-path", (project) => buildPlanningSplitChange(project, { ref: input.ref as AgentObjectRef, vertexIndex: input.vertexIndex as number })) },
    { name: "prepare_duplicate_project_objects", title: "Prepare object duplication", description: "Prepare copying terrain, equipment, locations, buildings with contents, or rooms; the editor generates ids/names.", inputSchema: { type: "object", properties: { refs: refsSchema }, required: ["refs"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "duplicate", (project) => buildDuplicateChange(project, bridge.getActivePlaceId(), refs(input))) },
    { name: "prepare_merge_project_objects", title: "Prepare region merging", description: "Prepare merging regions of one type: terrain, equipment, locations, buildings, or rooms. Building merges may preserve partitions.", inputSchema: { type: "object", properties: { refs: { ...refsSchema, minItems: 2 }, mode: { type: "string", enum: ["outer-only", "keep-partitions"] } }, required: ["refs"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "merge", (project) => buildMergeChange(project, bridge.getActivePlaceId(), refs(input), input.mode as "outer-only" | "keep-partitions" | undefined)) },
    { name: "prepare_delete_project_objects", title: "Prepare object deletion", description: "Prepare deleting selected objects; deleting a place includes all map objects inside. Preview reports the exact count.", inputSchema: { type: "object", properties: { refs: refsSchema, boundaryEditing: { type: "boolean" } }, required: ["refs"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "delete", (project) => buildDeleteChange(project, bridge.getActivePlaceId(), refs(input), input.boundaryEditing === true)) },
    { name: "prepare_resize_project_object", title: "Prepare object resizing", description: "Prepare resizing a region from a corner or changing door/window/gate/passage width.", inputSchema: { type: "object", properties: { ref: objectRefSchema, corner: { type: "string", enum: ["north-west", "north-east", "south-east", "south-west"] }, point: pointSchema, openingWidth: { type: "number", exclusiveMinimum: 0 } }, required: ["ref"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "resize", (project) => buildResizeChange(project, bridge.getActivePlaceId(), { ref: input.ref as AgentObjectRef, corner: input.corner as never, point: input.point as never, openingWidth: input.openingWidth as number | undefined })) },
    { name: "prepare_move_wall_endpoint", title: "Prepare moving one wall endpoint", description: "Prepare moving one wall end; the construction engine reconciles room geometry.", inputSchema: { type: "object", properties: { wallId: { type: "string" }, endpoint: { type: "string", enum: ["start", "end"] }, point: pointSchema, boundaryEditing: { type: "boolean" } }, required: ["wallId", "endpoint", "point"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "wall-endpoint", (project) => buildWallEndpointChange(project, bridge.getActivePlaceId(), { wallId: text(input, "wallId"), endpoint: input.endpoint as "start" | "end", point: input.point as never, boundaryEditing: input.boundaryEditing === true })) },
    { name: "prepare_add_to_outline", title: "Prepare extending an outline", description: "Prepare adding a connected region to terrain, surface, location, building, or level outline. Levels rebuild boundary walls/rooms.", inputSchema: { type: "object", properties: { target: { type: "object", properties: { kind: { type: "string", enum: ["element", "surface", "place"] }, id: { type: "string" } }, required: ["kind", "id"], additionalProperties: false }, shape: regionShapeSchema }, required: ["target", "shape"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "add-to-outline", (project) => { const target = input.target as { kind: "element" | "surface" | "place"; id: string }; const result = addRegionToOutline(project, bridge.getActivePlaceId(), target, regionShape(input.shape), { createId: () => crypto.randomUUID(), createRoomName: (index: number) => `Pomieszczenie ${index}` }); if (result.state === "blocked") throw new Error(result.reason); return { project: result.project, summary: `Rozszerzono obrys ${target.kind}:${target.id}.`, effects: [`outline-extended:${target.kind}:${target.id}`] }; }) },
    { name: "prepare_cut_map_hole", title: "Prepare cutting a hole in a region", description: "Prepare subtracting an area from editable terrain, object, surface, or outline. A crossing cutter removes only its intersection; floor cuts affect that floor, building cuts intersected floors. Preserve voids and surviving wall openings.", inputSchema: { type: "object", properties: { target: { type: "object", properties: { kind: { type: "string", enum: ["element", "surface", "place"] }, id: { type: "string" } }, required: ["kind", "id"], additionalProperties: false }, shape: regionShapeSchema }, required: ["target", "shape"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "cutout", (project) => buildCutoutChange(project, bridge.getActivePlaceId(), input.target as { kind: "element" | "surface" | "place"; id: string }, regionShape(input.shape))) },
    { name: "prepare_change_project_hierarchy", title: "Prepare a hierarchy change", description: "Prepare adding world/location/building/floor, moving a place, or reordering floors.", inputSchema: { type: "object", properties: { action: { type: "string", enum: ["add-map-level", "add-building-level", "reorder-level", "reparent-place"] }, placeId: { type: "string" }, kind: { type: "string", enum: ["world", "location", "building", "custom", "level"] }, name: { type: "string" }, locale: { type: "string", enum: ["pl", "en"] }, buildingId: { type: "string" }, position: { type: "string", enum: ["above", "below"] }, levelId: { type: "string" }, beforeLevelId: { type: "string" }, parentId: { type: "string" } }, required: ["action"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "hierarchy", (project) => buildHierarchyChange(project, hierarchyInput(input))) },
    { name: "prepare_clear_map_layer", title: "Prepare clearing one map layer", description: "Prepare removing every object on a layer. Construction categories: walls, stairs/lifts, platforms/balconies, doors, windows, gates/passages; legacy openings clears all wall openings.", inputSchema: { type: "object", properties: { layerId: { type: "string", enum: layers }, category: { type: "string", enum: constructionClearCategories } }, required: ["layerId"], additionalProperties: false }, annotations: mutating, execute: async (input) => prepare(coordinator, "clear-layer", (project) => buildClearLayerChange(project, bridge.getActivePlaceId(), text(input, "layerId") as never, (input.category as never) ?? "all")) },
    { name: "apply_prepared_editor_change", title: "Apply a prepared editor change", description: "Apply a validated token as one undoable transaction. This is a concurrency check, not extra human approval; large changes preserve a safety tracing first.", inputSchema: preparedTokenSchema, annotations: mutating, execute: async (input) => response(await coordinator.applyWithSafety(text(input, "token"))) },
    { name: "discard_prepared_editor_change", title: "Discard a prepared editor change", description: "Discard a preview token without changing the project.", inputSchema: preparedTokenSchema, annotations: mutating, execute: async (input) => response(coordinator.discard(text(input, "token"))) },
    { name: "open_map_level", title: "Open an exact map level", description: "Open a world, location, building, level, or room without changing project data.", inputSchema: { type: "object", properties: { placeId: { type: "string" } }, required: ["placeId"], additionalProperties: false }, annotations: mutating, execute: async (input) => { const id = text(input, "placeId"); const changed = bridge.openPlace?.(id) ?? bridge.getSession().openPlace(id).changed; if (changed && !bridge.openPlace) bridge.refresh(); return response({ status: changed ? "opened" : "blocked", placeId: id }); } },
    { name: "undo_editor_change", title: "Undo the last editor change", description: "Undo one committed editor transaction.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: mutating, execute: async () => { const result = bridge.getSession().undo(); if (result.changed) bridge.refresh(); return response({ status: result.changed ? "undone" : "no-change", code: result.code }); } },
    { name: "redo_editor_change", title: "Redo the last editor change", description: "Redo one previously undone editor transaction.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: mutating, execute: async () => { const result = bridge.getSession().redo(); if (result.changed) bridge.refresh(); return response({ status: result.changed ? "redone" : "no-change", code: result.code }); } },
    { name: "inspect_editor_history", title: "Inspect editor history", description: "Read undo/redo availability and the current session revision fingerprint. Read-only.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async () => response({ ...bridge.getSession().getHistoryState(), revision: coordinator.revision() }) },
    { name: "focus_project_objects", title: "Focus project objects", description: "Focus scoped objects on the shared sheet. Cross-sheet, missing, or ambiguous targets are unavailable; focus each sheet separately.", inputSchema: { type: "object", properties: { refs: refsSchema }, required: ["refs"], additionalProperties: false }, annotations: mutating, execute: async (input) => { const selected = refs(input); const focused = bridge.focusObjects?.(selected); return response({ status: bridge.focusObjects && focused !== false ? "focused" : "unavailable", refs: selected }); } },
    { name: "clear_agent_focus", title: "Clear agent focus", description: "Remove temporary object focus without changing project data.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: mutating, execute: async () => { bridge.clearFocus?.(); return response({ status: bridge.clearFocus ? "cleared" : "unavailable" }); } },
    { name: "list_project_checkpoints", title: "List project versions and tracing sheets", description: "List saved checkpoints for comparison or overlay. Read-only.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async () => response({ checkpoints: (bridge.getCheckpoints?.() ?? []).map(({ id, projectId, name, createdAt, kind, summary }) => ({ id, projectId, name, createdAt, kind: kind ?? "manual", summary })) }) },
    { name: "create_project_checkpoint", title: "Create a project checkpoint", description: "Create a recoverable snapshot and return a compact receipt; includeSnapshot=true returns the full export only when explicitly needed. Adds a version without changing map geometry.", inputSchema: { type: "object", properties: { name: { type: "string" }, includeSnapshot: { type: "boolean" } }, required: ["name"], additionalProperties: false }, annotations: mutating, execute: async (input) => {
      const checkpoint = await bridge.createCheckpoint?.(text(input, "name"));
      if (!checkpoint) return response({ status: "unavailable" });
      const receipt = { id: checkpoint.id, projectId: checkpoint.projectId, name: checkpoint.name, createdAt: checkpoint.createdAt, revision: projectRevision(checkpoint.snapshot), snapshotSize: JSON.stringify(checkpoint.snapshot).length, ...(input.includeSnapshot === true ? { snapshot: checkpoint.snapshot } : {}) };
      return response({ status: "created", checkpoint: receipt });
    } },
    { name: "compare_checkpoint_to_current", title: "Compare a checkpoint with the current project", description: "Read compact place, element, and construction counts added, removed, or changed since a checkpoint.", inputSchema: { type: "object", properties: { checkpointId: { type: "string" } }, required: ["checkpointId"], additionalProperties: false }, annotations: { readOnlyHint: true }, execute: async (input) => { const session = bridge.getSession(); const checkpoint = await fullCheckpoint(bridge, text(input, "checkpointId")); if (bridge.getSession() !== session) return response({ status: "stale" }); return response(checkpoint && checkpoint.projectId === session.getViewState().project.id ? { status: "compared", checkpointId: checkpoint.id, changes: projectDiff(checkpoint.snapshot, session.getState().project) } : { status: "not-found" }); } },
    { name: "prepare_restore_checkpoint", title: "Prepare restoring a checkpoint", description: "Prepare replacing current map state with a saved checkpoint. Application remains one undoable editor transaction.", inputSchema: { type: "object", properties: { checkpointId: { type: "string" } }, required: ["checkpointId"], additionalProperties: false }, annotations: mutating, execute: async (input) => { const session = bridge.getSession(); const before = session.getViewState().project; const id = text(input, "checkpointId"); const checkpoint = await fullCheckpoint(bridge, id); if (bridge.getSession() !== session || session.getViewState().project !== before) return response({ status: "stale" }); return prepare(coordinator, "restore-checkpoint", (project) => { if (!checkpoint || checkpoint.projectId !== project.id || checkpoint.snapshot.id !== project.id) throw new Error("checkpoint-not-found"); assertProposalCurrent(checkpoint, project); return { project: { ...structuredClone(checkpoint.snapshot), id: project.id, updatedAt: project.updatedAt }, summary: `Przywrócenie wersji ${checkpoint.name}.`, effects: [`restored:checkpoint:${id}`] }; }); } },
    { name: "prepare_delete_checkpoint", title: "Prepare deleting a checkpoint", description: "Prepare permanent deletion of one saved checkpoint without changing the current map.", inputSchema: { type: "object", properties: { checkpointId: { type: "string" } }, required: ["checkpointId"], additionalProperties: false }, annotations: mutating, execute: async (input) => { const id = text(input, "checkpointId"); const checkpoint = bridge.getCheckpoints?.().find((candidate) => candidate.id === id); if (!checkpoint) return response({ status: "not-found" }); const token = crypto.randomUUID(); pendingCheckpointDeletes.set(token, id); return response({ status: "prepared", token, checkpoint: { id, name: checkpoint.name, createdAt: checkpoint.createdAt } }); } },
    { name: "apply_checkpoint_deletion", title: "Apply checkpoint deletion", description: "Permanently delete exactly the checkpoint named by a prepared token.", inputSchema: preparedTokenSchema, annotations: mutating, execute: async (input) => { const token = text(input, "token"); const id = pendingCheckpointDeletes.get(token); if (!id) return response({ status: "not-found" }); const deleted = await bridge.deleteCheckpoint?.(id); if (deleted) pendingCheckpointDeletes.delete(token); return response({ status: deleted ? "deleted" : "blocked", checkpointId: id }); } },
    { name: "show_checkpoint_overlay", title: "Show a checkpoint as a tracing sheet", description: "Temporarily overlay a checkpoint at the requested opacity without changing project data.", inputSchema: { type: "object", properties: { checkpointId: { type: "string" }, opacity: { type: "number", minimum: 0.05, maximum: 1 } }, required: ["checkpointId"], additionalProperties: false }, annotations: mutating, execute: async (input) => response({ status: bridge.showCheckpoint?.(text(input, "checkpointId"), input.opacity as number | undefined) ? "shown" : "not-found" }) },
    { name: "hide_checkpoint_overlay", title: "Hide the checkpoint tracing sheet", description: "Hide the temporary checkpoint overlay without changing project data.", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: mutating, execute: async () => { bridge.showCheckpoint?.(undefined); return response({ status: bridge.showCheckpoint ? "hidden" : "unavailable" }); } },
  ];
}
